baseURL = "http://trangsempire.github.io/"
publishDir = "public"
languageCode = "en-us"
title = "Pastel Cravings"
theme = "penguin"
enableEmoji = true
paginate = 6
[blackfriday]
    extensions = ["hardLineBreak"]
[taxonomies]
  category = "categories"
  featured = "featured"