baseURL: 'http://pastelcravings.ca/'
publishDir: Trangsempire.github.io
languageCode: en-us
title: Pastel Cravings
theme: penguin
enableEmoji: true
paginate: 6
params:
  author: Trang Tran
  banner: hero.jpg
  developer: William Le
  instagram: 'https://www.instagram.com/pastel_cravings/'
  facebook: 'https://www.facebook.com/pastelcravings/'
  email: pauline_tran@outlook.com
  logo: logo3.png
  description: A blog dedicated to the most satisfying pleasure in life. And no, I'm not talking about sex. But food.
blackfriday:
  extensions:
    - hardLineBreak
  fractions: false
taxonomies:
  category: categories
  tag: tags
  featured: featured
  author: authors
