baseURL = "http://trangsempire.github.io/"
publishDir = "public"
languageCode = "en-us"
title = "Pastel Cravings"
theme = "chicken"
enableEmoji= true
[blackfriday]
    extensions = ["hardLineBreak"]
[taxonomies]
  category = "categories"
  featured = "featured"